# Generated by Django 5.2 on 2025-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_on_get',
            field=models.CharField(default='Картою', verbose_name='Оплата при отриманні'),
        ),
    ]
