# Generated by Django 5.2 on 2025-05-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='id',
            field=models.PositiveIntegerField(blank=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
