# Generated by Django 5.1.7 on 2025-04-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_categories_func_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='func_name',
        ),
    ]
