<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-09 13:17
=======
# Generated by Django 4.2.1 on 2025-03-30 11:32
>>>>>>> 2bcde29b6c4e3882e13e228b684f1ed14d675d38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_profile_Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL')),
=======
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
>>>>>>> 2bcde29b6c4e3882e13e228b684f1ed14d675d38
            ],
            options={
                'verbose_name': 'Кнопка профілю',
                'verbose_name_plural': 'Кнопки профілю',
                'db_table': 'my_profile_buttons',
            },
        ),
    ]
