# Generated by Django 5.1.7 on 2025-04-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_profile_Buttons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Кнопка профілю',
                'verbose_name_plural': 'Кнопки профілю',
                'db_table': 'my_profile_buttons',
            },
        ),
    ]
