# Generated by Django 4.2.1 on 2025-03-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Normal_Food',
        ),
    ]
