# Generated by Django 4.2.1 on 2025-03-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_my_profile_buttons_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_profile_buttons',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL'),
        ),
    ]
